using Godot;
using System;
using System.Collections.Generic;
using System.Security.Cryptography;

public partial class PolicyPresetsPanel : Panel
{
	private VBoxContainer Policies;
	private readonly Dictionary<string, Dictionary<string, object>> PolicyPresets = new Dictionary<string, Dictionary<string, object>>
	{
		{
			"Democratic Socialist", new Dictionary<string, object>
			{
				{"WealthTax", true},
				{"FinancialLiteracyClasses", true},
				{"RehibilationPrograms", true},
				{"AffordableHousing", true},
				{"HighSpeedRail", true},
				{"WaterInfrastrucutreUpgrades", true},
				{"MinimumWage", true},
				{"UnionFunding", true},
				{"RightToWork", false},
				{"UBI", true},
				{"SmallBuisnessSubsidies", false},
				{"PublicOwnershipOfMajorIndustries", true},
				{"WealthyTaxCuts", false},
				{"Deregulation", false},
				{"TransactionTax", true},
				{"CarbonTax", true},
				{"FreeTrade", false},
				{"PharmaCare", true},
				{"FreeMentalHealth", true},
				{"RareDeseaseResearch", true},
				{"DrugDecrim", true},
				{"DrugPriceCaps", true},
				{"LongTermCareFunding", true},
				{"UniversalHealthCare", true},
				{"FreeUniversityTuition", true},
				{"PublicSchoolFunding", true},
				{"SchoolVouchers", false},
				{"StudentLoanElim", true},
				{"NationalCurriculum", true},
				{"TeacherSalaryIncrease", true},
				{"FinacialLiteracyClasses", false},
				{"STEMFunding", true},
				{"PrivateSchoolBan", true},
				{"SingleUsePlasticsBan", true},
				{"RenewableEnergyInvestements", true},
				{"FossileFuelPhaseOut", true},
				{"NationalParkExpansion", true},
				{"2050CarbonNeutrality", true},
				{"EVSubsidies", false},
				{"PolutionRegs", true},
				{"NuclearEnergy", true},
				{"FrackingBan", true},
				{"UniversalChildCare", true},
				{"GunControl", true},
				{"Abortion", true},
				{"GayMarriage", true},
				{"GenderNeutralRestrooms", true},
				{"ConversionTherapyBan", true},
				{"InformedConsent", true},
				{"LegalSexWork", true},
				{"PaidParentalLeave", true},
				{"IndigenousFunding", true},
				{"PoliceFundingIncrease", false},
				{"MandatoryBodyCams", true},
				{"CriminalJusticeReform", true},
				{"MinimumSentencing", false},
				{"DeathPenalty", false},
				{"PrivatePrisonBan", true},
				{"IncreasedSurveilance", false},
				{"OpenBorders", false},
				{"IncreasedFundingForImmigration", true},
				{"BorderWall", false},
				{"PathwayToCitizenship", true},
				{"MassDeportation", false},
				{"RefugeeResettlementProgram", false},
				{"PointsBasedImmigration", false},
				{"BanFromSpecific", false},
				{"PublicTransportPolicy", true},
				{"GovernmentHighSpeedInternet", true},
				{"HighwayExpansion", false},
				{"WaterInfrastructureUpgrades", true},
				{"UrbanRenewal", true},
				{"Withdrawl", true},
				{"IncreasedDefenseSpending", true},
				{"NATOSupport", false},
				{"EconomicSanctions", true},
				{"HumanatarianAid", true},
				{"ClimateTreaties", true},
				{"MilataryAlliances", true},
				{"TradeEmbargoes", true},
				{"AIResearchFunding", true},
				{"BigTechReg", true},
				{"FacialTechBan", true},
				{"InternetPrivacyLaws", true},
				{"GreenTechTaxCredit", false},
				{"UniversalInternet", true},
				{"CryptoAdoption", false},
				{"LowerIncomeTax", "Maintain"},
				{"MiddleIncomeTax", "Increase"},
				{"HighIncomeTax", "Increase"},
				{"FlatIncomeTax", false},
				{"CorprateTax", "Increase"},
				{"SalesTax", false},
				{"LuxuryGoodsTax", true},
				{"InherentenceTax", true},
				{"CapitalGainsTax", true},
				{"QuebecIndependence", false},
				{"Bilingualism", true}
			}
		},
		{
			"Social Democrat", new Dictionary<string, object>
			{
				{"WealthTax", true},
				{"FinancialLiteracyClasses", true},
				{"RehibilationPrograms", true},
				{"AffordableHousing", true},
				{"HighSpeedRail", true},
				{"WaterInfrastrucutreUpgrades", true},
				{"MinimumWage", true},
				{"UnionFunding", false},
				{"RightToWork", false},
				{"UBI", true},
				{"SmallBuisnessSubsidies", true},
				{"PublicOwnershipOfMajorIndustries", false},
				{"WealthyTaxCuts", false},
				{"Deregulation", false},
				{"TransactionTax", false},
				{"CarbonTax", true},
				{"FreeTrade", true},
				{"PharmaCare", true},
				{"FreeMentalHealth", true},
				{"RareDeseaseResearch", true},
				{"DrugDecrim", true},
				{"DrugPriceCaps", true},
				{"LongTermCareFunding", true},
				{"UniversalHealthCare", true},
				{"FreeUniversityTuition", true},
				{"PublicSchoolFunding", true},
				{"SchoolVouchers", false},
				{"StudentLoanElim", true},
				{"NationalCurriculum", true},
				{"TeacherSalaryIncrease", true},
				{"FinacialLiteracyClasses", false},
				{"STEMFunding", true},
				{"PrivateSchoolBan", true},
				{"SingleUsePlasticsBan", true},
				{"RenewableEnergyInvestements", true},
				{"FossileFuelPhaseOut", true},
				{"NationalParkExpansion", true},
				{"2050CarbonNeutrality", true},
				{"EVSubsidies", true},
				{"PolutionRegs", true},
				{"NuclearEnergy", true},
				{"FrackingBan", true},
				{"UniversalChildCare", true},
				{"GunControl", true},
				{"Abortion", true},
				{"GayMarriage", true},
				{"GenderNeutralRestrooms", true},
				{"ConversionTherapyBan", true},
				{"InformedConsent", true},
				{"LegalSexWork", true},
				{"PaidParentalLeave", true},
				{"IndigenousFunding", true},
				{"PoliceFundingIncrease", false},
				{"MandatoryBodyCams", true},
				{"CriminalJusticeReform", true},
				{"MinimumSentencing", false},
				{"DeathPenalty", false},
				{"PrivatePrisonBan", true},
				{"IncreasedSurveilance", false},
				{"OpenBorders", false},
				{"IncreasedFundingForImmigration", true},
				{"BorderWall", false},
				{"PathwayToCitizenship", true},
				{"MassDeportation", false},
				{"RefugeeResettlementProgram", false},
				{"PointsBasedImmigration", true},
				{"BanFromSpecific", false},
				{"PublicTransportPolicy", true},
				{"GovernmentHighSpeedInternet", true},
				{"HighwayExpansion", true},
				{"WaterInfrastructureUpgrades", true},
				{"UrbanRenewal", true},
				{"Withdrawl", true},
				{"IncreasedDefenseSpending", true},
				{"NATOSupport", true},
				{"EconomicSanctions", true},
				{"HumanatarianAid", true},
				{"ClimateTreaties", true},
				{"MilataryAlliances", true},
				{"TradeEmbargoes", true},
				{"AIResearchFunding", true},
				{"BigTechReg", true},
				{"FacialTechBan", true},
				{"InternetPrivacyLaws", true},
				{"GreenTechTaxCredit", true},
				{"UniversalInternet", true},
				{"CryptoAdoption", false},
				{"LowerIncomeTax", "Maintain"},
				{"MiddleIncomeTax", "Maintain"},
				{"HighIncomeTax", "Increase"},
				{"FlatIncomeTax", false},
				{"CorprateTax", "Increase"},
				{"SalesTax", false},
				{"LuxuryGoodsTax", false},
				{"InherentenceTax", true},
				{"CapitalGainsTax", true},
				{"QuebecIndependence", false},
				{"Bilingualism", true}
			}
		},
		{
			"Progressive", new Dictionary<string, object>
			{
				{"WealthTax", false},
				{"FinancialLiteracyClasses", true},
				{"RehibilationPrograms", true},
				{"AffordableHousing", true},
				{"HighSpeedRail", true},
				{"WaterInfrastrucutreUpgrades", true},
				{"MinimumWage", true},
				{"UnionFunding", false},
				{"RightToWork", false},
				{"UBI", true},
				{"SmallBuisnessSubsidies", true},
				{"PublicOwnershipOfMajorIndustries", false},
				{"WealthyTaxCuts", false},
				{"Deregulation", false},
				{"TransactionTax", false},
				{"CarbonTax", true},
				{"FreeTrade", true},
				{"PharmaCare", true},
				{"FreeMentalHealth", true},
				{"RareDeseaseResearch", true},
				{"DrugDecrim", true},
				{"DrugPriceCaps", true},
				{"LongTermCareFunding", true},
				{"UniversalHealthCare", true},
				{"FreeUniversityTuition", true},
				{"PublicSchoolFunding", true},
				{"SchoolVouchers", false},
				{"StudentLoanElim", true},
				{"NationalCurriculum", true},
				{"TeacherSalaryIncrease", true},
				{"FinacialLiteracyClasses", false},
				{"STEMFunding", true},
				{"PrivateSchoolBan", false},
				{"SingleUsePlasticsBan", true},
				{"RenewableEnergyInvestements", true},
				{"FossileFuelPhaseOut", true},
				{"NationalParkExpansion", true},
				{"2050CarbonNeutrality", true},
				{"EVSubsidies", true},
				{"PolutionRegs", true},
				{"NuclearEnergy", true},
				{"FrackingBan", true},
				{"UniversalChildCare", true},
				{"GunControl", true},
				{"Abortion", true},
				{"GayMarriage", true},
				{"GenderNeutralRestrooms", true},
				{"ConversionTherapyBan", true},
				{"InformedConsent", true},
				{"LegalSexWork", true},
				{"PaidParentalLeave", true},
				{"IndigenousFunding", true},
				{"PoliceFundingIncrease", false},
				{"MandatoryBodyCams", true},
				{"CriminalJusticeReform", true},
				{"MinimumSentencing", false},
				{"DeathPenalty", false},
				{"PrivatePrisonBan", true},
				{"IncreasedSurveilance", false},
				{"OpenBorders", false},
				{"IncreasedFundingForImmigration", true},
				{"BorderWall", false},
				{"PathwayToCitizenship", true},
				{"MassDeportation", false},
				{"RefugeeResettlementProgram", false},
				{"PointsBasedImmigration", true},
				{"BanFromSpecific", true},
				{"PublicTransportPolicy", true},
				{"GovernmentHighSpeedInternet", true},
				{"HighwayExpansion", true},
				{"WaterInfrastructureUpgrades", true},
				{"UrbanRenewal", true},
				{"Withdrawl", true},
				{"IncreasedDefenseSpending", true},
				{"NATOSupport", true},
				{"EconomicSanctions", true},
				{"HumanatarianAid", true},
				{"ClimateTreaties", true},
				{"MilataryAlliances", true},
				{"TradeEmbargoes", true},
				{"AIResearchFunding", true},
				{"BigTechReg", true},
				{"FacialTechBan", true},
				{"InternetPrivacyLaws", true},
				{"GreenTechTaxCredit", true},
				{"UniversalInternet", true},
				{"CryptoAdoption", false},
				{"LowerIncomeTax", "Decrease"},
				{"MiddleIncomeTax", "Decrease"},
				{"HighIncomeTax", "Increase"},
				{"FlatIncomeTax", false},
				{"CorprateTax", "Increase"},
				{"SalesTax", true},
				{"LuxuryGoodsTax", false},
				{"InherentenceTax", false},
				{"CapitalGainsTax", true},
				{"QuebecIndependence", false},
				{"Bilingualism", true}
			}
		},
		{
			"Liberal", new Dictionary<string, object>
			{
				{"WealthTax", false},
				{"FinancialLiteracyClasses", true},
				{"RehibilationPrograms", true},
				{"AffordableHousing", true},
				{"HighSpeedRail", true},
				{"WaterInfrastrucutreUpgrades", true},
				{"MinimumWage", true},
				{"UnionFunding", false},
				{"RightToWork", false},
				{"UBI", false},
				{"SmallBuisnessSubsidies", true},
				{"PublicOwnershipOfMajorIndustries", false},
				{"WealthyTaxCuts", false},
				{"Deregulation", false},
				{"TransactionTax", false},
				{"CarbonTax", true},
				{"FreeTrade", true},
				{"PharmaCare", false},
				{"FreeMentalHealth", false},
				{"RareDeseaseResearch", true},
				{"DrugDecrim", true},
				{"DrugPriceCaps", true},
				{"LongTermCareFunding", true},
				{"UniversalHealthCare", true},
				{"FreeUniversityTuition", false},
				{"PublicSchoolFunding", true},
				{"SchoolVouchers", true},
				{"StudentLoanElim", false},
				{"NationalCurriculum", false},
				{"TeacherSalaryIncrease", true},
				{"STEMFunding", true},
				{"PrivateSchoolBan", false},
				{"SingleUsePlasticsBan", true},
				{"RenewableEnergyInvestements", true},
				{"FossileFuelPhaseOut", true},
				{"NationalParkExpansion", true},
				{"2050CarbonNeutrality", true},
				{"EVSubsidies", true},
				{"PolutionRegs", true},
				{"NuclearEnergy", true},
				{"FrackingBan", false},
				{"UniversalChildCare", true},
				{"GunControl", true},
				{"Abortion", true},
				{"GayMarriage", true},
				{"GenderNeutralRestrooms", true},
				{"ConversionTherapyBan", true},
				{"InformedConsent", true},
				{"LegalSexWork", false},
				{"PaidParentalLeave", true},
				{"IndigenousFunding", true},
				{"PoliceFundingIncrease", true},
				{"MandatoryBodyCams", true},
				{"CriminalJusticeReform", true},
				{"MinimumSentencing", true},
				{"DeathPenalty", false},
				{"PrivatePrisonBan", false},
				{"IncreasedSurveilance", true},
				{"OpenBorders", false},
				{"IncreasedFundingForImmigration", true},
				{"BorderWall", false},
				{"PathwayToCitizenship", true},
				{"MassDeportation", false},
				{"RefugeeResettlementProgram", false},
				{"PointsBasedImmigration", true},
				{"BanFromSpecific", false},
				{"PublicTransportPolicy", true},
				{"GovernmentHighSpeedInternet", false},
				{"HighwayExpansion", true},
				{"WaterInfrastructureUpgrades", true},
				{"UrbanRenewal", true},
				{"Withdrawl", true},
				{"IncreasedDefenseSpending", true},
				{"NATOSupport", true},
				{"EconomicSanctions", true},
				{"HumanatarianAid", true},
				{"ClimateTreaties", true},
				{"MilataryAlliances", true},
				{"TradeEmbargoes", true},
				{"AIResearchFunding", true},
				{"BigTechReg", true},
				{"FacialTechBan", true},
				{"InternetPrivacyLaws", false},
				{"GreenTechTaxCredit", true},
				{"UniversalInternet", false},
				{"CryptoAdoption", false},
				{"LowerIncomeTax", "Decrease"},
				{"MiddleIncomeTax", "Decrease"},
				{"HighIncomeTax", "Increase"},
				{"FlatIncomeTax", false},
				{"CorprateTax", "Maintain"},
				{"SalesTax", true},
				{"LuxuryGoodsTax", false},
				{"InherentenceTax", false},
				{"CapitalGainsTax", true},
				{"QuebecIndependence", false},
				{"Bilingualism", true}
			}
		},
		{
			"Blue Liberal", new Dictionary<string, object>
			{
				{"WealthTax", false},
				{"FinancialLiteracyClasses", true},
				{"RehibilationPrograms", true},
				{"AffordableHousing", true},
				{"HighSpeedRail", true},
				{"WaterInfrastrucutreUpgrades", true},
				{"MinimumWage", false},
				{"UnionFunding", false},
				{"RightToWork", false},
				{"UBI", false},
				{"SmallBuisnessSubsidies", true},
				{"PublicOwnershipOfMajorIndustries", false},
				{"WealthyTaxCuts", false},
				{"Deregulation", true},
				{"TransactionTax", false},
				{"CarbonTax", false},
				{"FreeTrade", true},
				{"PharmaCare", false},
				{"FreeMentalHealth", false},
				{"RareDeseaseResearch", true},
				{"DrugDecrim", false},
				{"DrugPriceCaps", false},
				{"LongTermCareFunding", false},
				{"UniversalHealthCare", true},
				{"FreeUniversityTuition", false},
				{"PublicSchoolFunding", true},
				{"SchoolVouchers", true},
				{"StudentLoanElim", false},
				{"NationalCurriculum", false},
				{"TeacherSalaryIncrease", true},
				{"STEMFunding", true},
				{"PrivateSchoolBan", false},
				{"SingleUsePlasticsBan", true},
				{"RenewableEnergyInvestements", true},
				{"FossileFuelPhaseOut", false},
				{"NationalParkExpansion", true},
				{"2050CarbonNeutrality", true},
				{"EVSubsidies", true},
				{"PolutionRegs", true},
				{"NuclearEnergy", true},
				{"FrackingBan", false},
				{"UniversalChildCare", false},
				{"GunControl", true},
				{"Abortion", true},
				{"GayMarriage", true},
				{"GenderNeutralRestrooms", true},
				{"ConversionTherapyBan", true},
				{"InformedConsent", true},
				{"LegalSexWork", false},
				{"PaidParentalLeave", false},
				{"IndigenousFunding", true},
				{"PoliceFundingIncrease", true},
				{"MandatoryBodyCams", true},
				{"CriminalJusticeReform", true},
				{"MinimumSentencing", true},
				{"DeathPenalty", false},
				{"PrivatePrisonBan", false},
				{"IncreasedSurveilance", true},
				{"OpenBorders", false},
				{"IncreasedFundingForImmigration", true},
				{"BorderWall", false},
				{"PathwayToCitizenship", true},
				{"MassDeportation", false},
				{"RefugeeResettlementProgram", false},
				{"PointsBasedImmigration", true},
				{"BanFromSpecific", true},
				{"PublicTransportPolicy", false},
				{"GovernmentHighSpeedInternet", false},
				{"HighwayExpansion", true},
				{"WaterInfrastructureUpgrades", false},
				{"UrbanRenewal", false},
				{"Withdrawl", true},
				{"IncreasedDefenseSpending", true},
				{"NATOSupport", true},
				{"EconomicSanctions", true},
				{"HumanatarianAid", true},
				{"ClimateTreaties", true},
				{"MilataryAlliances", true},
				{"TradeEmbargoes", true},
				{"AIResearchFunding", true},
				{"BigTechReg", false},
				{"FacialTechBan", false},
				{"InternetPrivacyLaws", false},
				{"GreenTechTaxCredit", true},
				{"UniversalInternet", false},
				{"CryptoAdoption", false},
				{"LowerIncomeTax", "Maintain"},
				{"MiddleIncomeTax", "Increase"},
				{"HighIncomeTax", "Decrease"},
				{"FlatIncomeTax", false},
				{"CorprateTax", "Maintain"},
				{"SalesTax", true},
				{"LuxuryGoodsTax", false},
				{"InherentenceTax", false},
				{"CapitalGainsTax", false},
				{"QuebecIndependence", false},
				{"Bilingualism", true}
			}
		},
		{
			"Red Tory", new Dictionary<string, object>
			{
				{"WealthTax", false},
				{"FinancialLiteracyClasses", true},
				{"RehibilationPrograms", false},
				{"AffordableHousing", true},
				{"HighSpeedRail", false},
				{"WaterInfrastrucutreUpgrades", true},
				{"MinimumWage", false},
				{"UnionFunding", false},
				{"RightToWork", false},
				{"UBI", false},
				{"SmallBuisnessSubsidies", false},
				{"PublicOwnershipOfMajorIndustries", false},
				{"WealthyTaxCuts", true},
				{"Deregulation", true},
				{"TransactionTax", false},
				{"CarbonTax", false},
				{"FreeTrade", false},
				{"PharmaCare", false},
				{"FreeMentalHealth", false},
				{"RareDeseaseResearch", false},
				{"DrugDecrim", false},
				{"DrugPriceCaps", false},
				{"LongTermCareFunding", true},
				{"UniversalHealthCare", true},
				{"FreeUniversityTuition", false},
				{"PublicSchoolFunding", false},
				{"SchoolVouchers", true},
				{"StudentLoanElim", false},
				{"NationalCurriculum", false},
				{"TeacherSalaryIncrease", true},
				{"STEMFunding", true},
				{"PrivateSchoolBan", false},
				{"SingleUsePlasticsBan", true},
				{"RenewableEnergyInvestements", true},
				{"FossileFuelPhaseOut", false},
				{"NationalParkExpansion", true},
				{"2050CarbonNeutrality", true},
				{"EVSubsidies", true},
				{"PolutionRegs", true},
				{"NuclearEnergy", true},
				{"FrackingBan", false},
				{"UniversalChildCare", false},
				{"GunControl", true},
				{"Abortion", true},
				{"GayMarriage", true},
				{"GenderNeutralRestrooms", true},
				{"ConversionTherapyBan", true},
				{"InformedConsent", true},
				{"LegalSexWork", false},
				{"PaidParentalLeave", false},
				{"IndigenousFunding", false},
				{"PoliceFundingIncrease", true},
				{"MandatoryBodyCams", true},
				{"CriminalJusticeReform", false},
				{"MinimumSentencing", true},
				{"DeathPenalty", false},
				{"PrivatePrisonBan", false},
				{"IncreasedSurveilance", true},
				{"OpenBorders", false},
				{"IncreasedFundingForImmigration", true},
				{"BorderWall", false},
				{"PathwayToCitizenship", false},
				{"MassDeportation", false},
				{"RefugeeResettlementProgram", false},
				{"PointsBasedImmigration", true},
				{"BanFromSpecific", false},
				{"PublicTransportPolicy", false},
				{"GovernmentHighSpeedInternet", false},
				{"HighwayExpansion", true},
				{"WaterInfrastructureUpgrades", false},
				{"UrbanRenewal", false},
				{"Withdrawl", true},
				{"IncreasedDefenseSpending", true},
				{"NATOSupport", true},
				{"EconomicSanctions", true},
				{"HumanatarianAid", true},
				{"ClimateTreaties", true},
				{"MilataryAlliances", true},
				{"TradeEmbargoes", true},
				{"AIResearchFunding", true},
				{"BigTechReg", false},
				{"FacialTechBan", false},
				{"InternetPrivacyLaws", false},
				{"GreenTechTaxCredit", true},
				{"UniversalInternet", false},
				{"CryptoAdoption", false},
				{"LowerIncomeTax", "Decrease"},
				{"MiddleIncomeTax", "Decrease"},
				{"HighIncomeTax", "Decrease"},
				{"FlatIncomeTax", false},
				{"CorprateTax", "Maintain"},
				{"SalesTax", true},
				{"LuxuryGoodsTax", false},
				{"InherentenceTax", false},
				{"CapitalGainsTax", false},
				{"QuebecIndependence", false},
				{"Bilingualism", false}
			}
		},
		{
			"Blue Tory", new Dictionary<string, object>
			{
				{"WealthTax", false},
				{"FinancialLiteracyClasses", true},
				{"RehibilationPrograms", false},
				{"AffordableHousing", false},
				{"HighSpeedRail", false},
				{"WaterInfrastrucutreUpgrades", false},
				{"MinimumWage", false},
				{"UnionFunding", false},
				{"RightToWork", true},
				{"UBI", false},
				{"SmallBuisnessSubsidies", true},
				{"PublicOwnershipOfMajorIndustries", false},
				{"WealthyTaxCuts", true},
				{"Deregulation", true},
				{"TransactionTax", false},
				{"CarbonTax", false},
				{"FreeTrade", true},
				{"PharmaCare", false},
				{"FreeMentalHealth", false},
				{"RareDeseaseResearch", false},
				{"DrugDecrim", false},
				{"DrugPriceCaps", false},
				{"LongTermCareFunding", false},
				{"UniversalHealthCare", true},
				{"FreeUniversityTuition", false},
				{"PublicSchoolFunding", false},
				{"SchoolVouchers", true},
				{"StudentLoanElim", false},
				{"NationalCurriculum", false},
				{"TeacherSalaryIncrease", false},
				{"STEMFunding", false},
				{"PrivateSchoolBan", false},
				{"SingleUsePlasticsBan", false},
				{"RenewableEnergyInvestements", true},
				{"FossileFuelPhaseOut", false},
				{"NationalParkExpansion", false},
				{"2050CarbonNeutrality", true},
				{"EVSubsidies", false},
				{"PolutionRegs", false},
				{"NuclearEnergy", true},
				{"FrackingBan", false},
				{"UniversalChildCare", false},
				{"GunControl", false},
				{"Abortion", true},
				{"GayMarriage", true},
				{"GenderNeutralRestrooms", false},
				{"ConversionTherapyBan", false},
				{"InformedConsent", false},
				{"LegalSexWork", false},
				{"PaidParentalLeave", false},
				{"IndigenousFunding", false},
				{"PoliceFundingIncrease", true},
				{"MandatoryBodyCams", false},
				{"CriminalJusticeReform", false},
				{"MinimumSentencing", true},
				{"DeathPenalty", false},
				{"PrivatePrisonBan", false},
				{"IncreasedSurveilance", true},
				{"OpenBorders", false},
				{"IncreasedFundingForImmigration", false},
				{"BorderWall", false},
				{"PathwayToCitizenship", false},
				{"MassDeportation", false},
				{"RefugeeResettlementProgram", true},
				{"PointsBasedImmigration", true},
				{"BanFromSpecific", false},
				{"PublicTransportPolicy", false},
				{"GovernmentHighSpeedInternet", false},
				{"HighwayExpansion", true},
				{"WaterInfrastructureUpgrades", true},
				{"UrbanRenewal", true},
				{"Withdrawl", false},
				{"IncreasedDefenseSpending", true},
				{"NATOSupport", true},
				{"EconomicSanctions", false},
				{"HumanatarianAid", false},
				{"ClimateTreaties", false},
				{"MilataryAlliances", true},
				{"TradeEmbargoes", false},
				{"AIResearchFunding", true},
				{"BigTechReg", false},
				{"FacialTechBan", false},
				{"InternetPrivacyLaws", false},
				{"GreenTechTaxCredit", false},
				{"UniversalInternet", false},
				{"CryptoAdoption", true},
				{"LowerIncomeTax", "Maintain"},
				{"MiddleIncomeTax", "Increase"},
				{"HighIncomeTax", "Decrease"},
				{"FlatIncomeTax", false},
				{"CorprateTax", "Decrease"},
				{"SalesTax", true},
				{"LuxuryGoodsTax", false},
				{"InherentenceTax", false},
				{"CapitalGainsTax", false},
				{"QuebecIndependence", false},
				{"Bilingualism", true}
			}
		},
		{
			"Conservative", new Dictionary<string, object>
			{
				{"WealthTax", false},
				{"FinancialLiteracyClasses", false},
				{"RehibilationPrograms", false},
				{"AffordableHousing", false},
				{"HighSpeedRail", false},
				{"WaterInfrastrucutreUpgrades", false},
				{"MinimumWage", false},
				{"UnionFunding", false},
				{"RightToWork", true},
				{"UBI", false},
				{"SmallBuisnessSubsidies", false},
				{"PublicOwnershipOfMajorIndustries", false},
				{"WealthyTaxCuts", true},
				{"Deregulation", true},
				{"TransactionTax", false},
				{"CarbonTax", false},
				{"FreeTrade", true},
				{"PharmaCare", false},
				{"FreeMentalHealth", false},
				{"RareDeseaseResearch", false},
				{"DrugDecrim", false},
				{"DrugPriceCaps", false},
				{"LongTermCareFunding", false},
				{"UniversalHealthCare", false},
				{"FreeUniversityTuition", false},
				{"PublicSchoolFunding", false},
				{"SchoolVouchers", true},
				{"StudentLoanElim", false},
				{"NationalCurriculum", false},
				{"TeacherSalaryIncrease", false},
				{"FinacialLiteracyClasses", false},
				{"STEMFunding", false},
				{"PrivateSchoolBan", false},
				{"SingleUsePlasticsBan", false},
				{"RenewableEnergyInvestements", false},
				{"FossileFuelPhaseOut", false},
				{"NationalParkExpansion", false},
				{"2050CarbonNeutrality", false},
				{"EVSubsidies", false},
				{"PolutionRegs", false},
				{"NuclearEnergy", true},
				{"FrackingBan", false},
				{"UniversalChildCare", false},
				{"GunControl", false},
				{"Abortion", false},
				{"GayMarriage", false},
				{"GenderNeutralRestrooms", false},
				{"ConversionTherapyBan", false},
				{"InformedConsent", false},
				{"LegalSexWork", false},
				{"PaidParentalLeave", false},
				{"IndigenousFunding", false},
				{"PoliceFundingIncrease", true},
				{"MandatoryBodyCams", false},
				{"CriminalJusticeReform", false},
				{"MinimumSentencing", true},
				{"DeathPenalty", true},
				{"PrivatePrisonBan", false},
				{"IncreasedSurveilance", true},
				{"OpenBorders", false},
				{"IncreasedFundingForImmigration", false},
				{"BorderWall", false},
				{"PathwayToCitizenship", false},
				{"MassDeportation", false},
				{"RefugeeResettlementProgram", true},
				{"PointsBasedImmigration", true},
				{"BanFromSpecific", true},
				{"PublicTransportPolicy", false},
				{"GovernmentHighSpeedInternet", false},
				{"HighwayExpansion", false},
				{"WaterInfrastructureUpgrades", false},
				{"UrbanRenewal", false},
				{"Withdrawl", true},
				{"IncreasedDefenseSpending", true},
				{"NATOSupport", true},
				{"EconomicSanctions", false},
				{"HumanatarianAid", false},
				{"ClimateTreaties", false},
				{"MilataryAlliances", true},
				{"TradeEmbargoes", true},
				{"AIResearchFunding", true},
				{"BigTechReg", false},
				{"FacialTechBan", false},
				{"InternetPrivacyLaws", false},
				{"GreenTechTaxCredit", false},
				{"UniversalInternet", false},
				{"CryptoAdoption", true},
				{"LowerIncomeTax", "Increase"},
				{"MiddleIncomeTax", "Increase"},
				{"HighIncomeTax", "Decrease"},
				{"FlatIncomeTax", false},
				{"CorprateTax", "Decrease"},
				{"SalesTax", true},
				{"LuxuryGoodsTax", false},
				{"InherentenceTax", false},
				{"CapitalGainsTax", false},
				{"QuebecIndependence", false},
				{"Bilingualism", false}
			}
		},
		{
			"Libertarian", new Dictionary<string, object>
			{
				{"WealthTax", false},
				{"FinancialLiteracyClasses", false},
				{"RehibilationPrograms", false},
				{"AffordableHousing", false},
				{"HighSpeedRail", false},
				{"WaterInfrastrucutreUpgrades", false},
				{"MinimumWage", false},
				{"UnionFunding", false},
				{"RightToWork", true},
				{"UBI", false},
				{"SmallBuisnessSubsidies", false},
				{"PublicOwnershipOfMajorIndustries", false},
				{"WealthyTaxCuts", true},
				{"Deregulation", true},
				{"TransactionTax", false},
				{"CarbonTax", false},
				{"FreeTrade", true},
				{"PharmaCare", false},
				{"FreeMentalHealth", false},
				{"RareDeseaseResearch", false},
				{"DrugDecrim", true},
				{"DrugPriceCaps", false},
				{"LongTermCareFunding", false},
				{"UniversalHealthCare", false},
				{"FreeUniversityTuition", false},
				{"PublicSchoolFunding", false},
				{"SchoolVouchers", false},
				{"StudentLoanElim", false},
				{"NationalCurriculum", false},
				{"TeacherSalaryIncrease", false},
				{"FinacialLiteracyClasses", false},
				{"STEMFunding", false},
				{"PrivateSchoolBan", false},
				{"SingleUsePlasticsBan", false},
				{"RenewableEnergyInvestements", false},
				{"FossileFuelPhaseOut", false},
				{"NationalParkExpansion", false},
				{"2050CarbonNeutrality", false},
				{"EVSubsidies", false},
				{"PolutionRegs", false},
				{"NuclearEnergy", false},
				{"FrackingBan", false},
				{"UniversalChildCare", false},
				{"GunControl", false},
				{"Abortion", true},
				{"GayMarriage", true},
				{"GenderNeutralRestrooms", true},
				{"ConversionTherapyBan", true},
				{"InformedConsent", true},
				{"LegalSexWork", true},
				{"PaidParentalLeave", false},
				{"IndigenousFunding", false},
				{"PoliceFundingIncrease", false},
				{"MandatoryBodyCams", false},
				{"CriminalJusticeReform", false},
				{"MinimumSentencing", false},
				{"DeathPenalty", false},
				{"PrivatePrisonBan", false},
				{"IncreasedSurveilance", false},
				{"OpenBorders", true},
				{"IncreasedFundingForImmigration", false},
				{"BorderWall", false},
				{"PathwayToCitizenship", false},
				{"MassDeportation", false},
				{"RefugeeResettlementProgram", false},
				{"PointsBasedImmigration", false},
				{"BanFromSpecific", false},
				{"PublicTransportPolicy", false},
				{"GovernmentHighSpeedInternet", false},
				{"HighwayExpansion", false},
				{"WaterInfrastructureUpgrades", false},
				{"UrbanRenewal", false},
				{"Withdrawl", true},
				{"IncreasedDefenseSpending", false},
				{"NATOSupport", false},
				{"EconomicSanctions", false},
				{"HumanatarianAid", false},
				{"ClimateTreaties", false},
				{"MilataryAlliances", false},
				{"TradeEmbargoes", false},
				{"AIResearchFunding", false},
				{"BigTechReg", false},
				{"FacialTechBan", false},
				{"InternetPrivacyLaws", false},
				{"GreenTechTaxCredit", false},
				{"UniversalInternet", false},
				{"CryptoAdoption", true},
				{"LowerIncomeTax", "Decrease"},
				{"MiddleIncomeTax", "Decrease"},
				{"HighIncomeTax", "Decrease"},
				{"FlatIncomeTax", true},
				{"CorprateTax", "Decrease"},
				{"SalesTax", false},
				{"LuxuryGoodsTax", false},
				{"InherentenceTax", false},
				{"CapitalGainsTax", false},
				{"QuebecIndependence", false},
				{"Bilingualism", false}
			}
		},
		{
			"Canadian Nationalist", new Dictionary<string, object>
			{
				{"WealthTax", false},
				{"FinancialLiteracyClasses", false},
				{"RehibilationPrograms", false},
				{"AffordableHousing", false},
				{"HighSpeedRail", false},
				{"WaterInfrastrucutreUpgrades", false},
				{"MinimumWage", false},
				{"UnionFunding", false},
				{"RightToWork", true},
				{"UBI", false},
				{"SmallBuisnessSubsidies", false},
				{"PublicOwnershipOfMajorIndustries", false},
				{"WealthyTaxCuts", true},
				{"Deregulation", true},
				{"TransactionTax", false},
				{"CarbonTax", false},
				{"FreeTrade", false},
				{"PharmaCare", false},
				{"FreeMentalHealth", false},
				{"RareDeseaseResearch", false},
				{"DrugDecrim", false},
				{"DrugPriceCaps", false},
				{"LongTermCareFunding", false},
				{"UniversalHealthCare", false},
				{"FreeUniversityTuition", false},
				{"PublicSchoolFunding", false},
				{"SchoolVouchers", true},
				{"StudentLoanElim", false},
				{"NationalCurriculum", false},
				{"TeacherSalaryIncrease", false},
				{"FinacialLiteracyClasses", false},
				{"STEMFunding", false},
				{"PrivateSchoolBan", false},
				{"SingleUsePlasticsBan", false},
				{"RenewableEnergyInvestements", false},
				{"FossileFuelPhaseOut", false},
				{"NationalParkExpansion", false},
				{"2050CarbonNeutrality", false},
				{"EVSubsidies", false},
				{"PolutionRegs", false},
				{"NuclearEnergy", false},
				{"FrackingBan", false},
				{"UniversalChildCare", false},
				{"GunControl", false},
				{"Abortion", false},
				{"GayMarriage", false},
				{"GenderNeutralRestrooms", false},
				{"ConversionTherapyBan", false},
				{"InformedConsent", false},
				{"LegalSexWork", false},
				{"PaidParentalLeave", false},
				{"IndigenousFunding", false},
				{"PoliceFundingIncrease", true},
				{"MandatoryBodyCams", false},
				{"CriminalJusticeReform", false},
				{"MinimumSentencing", true},
				{"DeathPenalty", true},
				{"PrivatePrisonBan", false},
				{"IncreasedSurveilance", true},
				{"OpenBorders", false},
				{"IncreasedFundingForImmigration", false},
				{"BorderWall", true},
				{"PathwayToCitizenship", false},
				{"MassDeportation", true},
				{"RefugeeResettlementProgram", true},
				{"PointsBasedImmigration", false},
				{"BanFromSpecific", true},
				{"PublicTransportPolicy", false},
				{"GovernmentHighSpeedInternet", false},
				{"HighwayExpansion", true},
				{"WaterInfrastructureUpgrades", false},
				{"UrbanRenewal", false},
				{"Withdrawl", true},
				{"IncreasedDefenseSpending", false},
				{"NATOSupport", false},
				{"EconomicSanctions", false},
				{"HumanatarianAid", false},
				{"ClimateTreaties", false},
				{"MilataryAlliances", false},
				{"TradeEmbargoes", false},
				{"AIResearchFunding", true},
				{"BigTechReg", false},
				{"FacialTechBan", false},
				{"InternetPrivacyLaws", false},
				{"GreenTechTaxCredit", false},
				{"UniversalInternet", false},
				{"CryptoAdoption", false},
				{"LowerIncomeTax", "Increase"},
				{"MiddleIncomeTax", "Increase"},
				{"HighIncomeTax", "Decrease"},
				{"FlatIncomeTax", true},
				{"CorprateTax", "Decrease"},
				{"SalesTax", true},
				{"LuxuryGoodsTax", false},
				{"InherentenceTax", false},
				{"CapitalGainsTax", false},
				{"QuebecIndependence", false},
				{"Bilingualism", false}
			}
		}
	};
     public override void _Ready()
    {
        Policies = GetNodeOrNull<VBoxContainer>("../ScrollContainer/PolicyBox");
        if (Policies == null)
        {
            GD.PrintErr("Policies container not found.");
        }
        else
        {
            GD.Print("Policies container successfully assigned.");
        }
        Visible = false;
        Policies.Visible = true;
    }

    public void _on_policy_presets_pressed()
    {
        Visible = true;
        Policies.Visible = false;
    }

    public void _on_dem_soc_pressed()
    {
        SetPolicyOptions("Democratic Socialist");
        ClosePanel();
    }
	public void _on_progressive_pressed()
	{
		SetPolicyOptions("Progressive");
		ClosePanel();
	}
	public void _on_liberal_pressed()
	{
		SetPolicyOptions("Liberal");
		ClosePanel();
	}

	public void _on_blue_liberal_pressed()
	{
		SetPolicyOptions("Blue Liberal");
		ClosePanel();
	}
	public void _on_red_tory_pressed()
	{
		SetPolicyOptions("Red Tory");
		ClosePanel();
	}
	public void _on_blue_tory_pressed()
	{
		SetPolicyOptions("Blue Tory");
		ClosePanel();
	}
	public void _on_conservative_pressed()
	{
		SetPolicyOptions("Conservative");
		ClosePanel();
	}
	public void _on_libretarian_pressed()
	{
		SetPolicyOptions("Libertarian");
		ClosePanel();
	}
	public void _on_nationalist_pressed()
	{
		SetPolicyOptions("Canadian Nationalist");
		ClosePanel();
	}


	private void SetPolicyOptions(string Preset)
	{
		if (!PolicyPresets.ContainsKey(Preset))
		{
			GD.PrintErr("Policy preset not found: " + Preset);
			return;
		}
		foreach (Node node in GetTree().GetNodesInGroup("PolicyGroup"))
		{
			if (node is CheckBox checkBox)
			{
				string PolicyName = checkBox.GetParent().GetParent().Name;
				if (PolicyPresets[Preset].ContainsKey(PolicyName)) // Check if our preset contains the policy
				{
					object PresetValue = PolicyPresets[Preset][PolicyName];
					if (PresetValue is bool isYes) // Corresponds to true
					{
						checkBox.SetPressedNoSignal((checkBox.Text == "Yes") == isYes);
					}
					else if (PresetValue is string PresetString)
					{
						checkBox.SetPressedNoSignal(checkBox.Text == PresetString);
					}
					GD.Print($"Set policy {PolicyName} to {PresetValue}");
				}
			}
		}
	}

    private void ClosePanel()
    {
        Visible = false;
        Policies.Visible = true;
    }
}
			





